-- Split into three files so each step is one paste. Nothing lives here any
-- more, so there is no second copy of the SQL to go stale -- which would be a
-- poor joke in a file about duplicated data.
--
--   1-check-drift.sql      read only; lists anything that already disagrees
--   2-install-triggers.sql the enforcement; run after reading step 1's result
--   3-uninstall.sql        removes it again, changing no data
--   4-verify.sql           read only; proves the four triggers exist and are on
--   5-email-threading.sql adds messages.email_message_id, so replies thread
--   6-usage-audit.sql     read only; what is consuming the free-tier database
--
-- Copy one to the clipboard with, e.g.:
--   pbcopy < tools/sql/1-check-drift.sql
--
-- Then paste into the Supabase SQL editor for the BOOKING project (not
-- MyFinance, which is a separate project).
